import { NextRequest } from "next/server";
import { createClient } from "@supabase/supabase-js";
import crypto from "crypto";

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
function verifyToken(token: string): boolean {
  try { const secret = process.env.ADMIN_PASSWORD; if (!secret) return false; const p = token.split("."); if (p.length !== 2) return false; const pl = JSON.parse(Buffer.from(p[0], "base64").toString()); if (crypto.createHmac("sha256", secret).update(p[0]).digest("base64url") !== p[1]) return false; if (Date.now() > pl.exp) return false; return true; } catch { return false; }
}
export async function GET(req: NextRequest) { const a = req.headers.get("authorization")?.replace("Bearer ", ""); if (!a || !verifyToken(a)) return Response.json({ error: "Unauthorized" }, { status: 401 }); const { data, error } = await supabase.from("team_members").select("*").order("order", { ascending: true }); if (error) return Response.json({ error: error.message }, { status: 500 }); return Response.json(data); }
export async function POST(req: NextRequest) { const a = req.headers.get("authorization")?.replace("Bearer ", ""); if (!a || !verifyToken(a)) return Response.json({ error: "Unauthorized" }, { status: 401 }); const b = await req.json(); const { data, error } = await supabase.from("team_members").insert([{ name: b.name, role: b.role || null, description: b.description || null, initials: b.initials || null, avatar: b.avatar || null, order: b.order || 0, published: b.published ?? true }]).select(); if (error) return Response.json({ error: error.message }, { status: 500 }); return Response.json(data?.[0] || null, { status: 201 }); }
export async function PUT(req: NextRequest) { const a = req.headers.get("authorization")?.replace("Bearer ", ""); if (!a || !verifyToken(a)) return Response.json({ error: "Unauthorized" }, { status: 401 }); const b = await req.json(); if (!b.id) return Response.json({ error: "id required" }, { status: 400 }); const { data, error } = await supabase.from("team_members").update({ name: b.name, role: b.role || null, description: b.description || null, initials: b.initials || null, avatar: b.avatar || null, order: b.order || 0, published: b.published ?? true }).eq("id", b.id).select(); if (error) return Response.json({ error: error.message }, { status: 500 }); return Response.json(data?.[0] || null); }
export async function DELETE(req: NextRequest) { const a = req.headers.get("authorization")?.replace("Bearer ", ""); if (!a || !verifyToken(a)) return Response.json({ error: "Unauthorized" }, { status: 401 }); const id = new URL(req.url).searchParams.get("id"); if (!id) return Response.json({ error: "id required" }, { status: 400 }); const { error } = await supabase.from("team_members").delete().eq("id", id); if (error) return Response.json({ error: error.message }, { status: 500 }); return Response.json({ success: true }); }
